
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 src/lib/components/models/barrel.glb -s
-->




    <script>

				
	
        import { Group } from 'three'
        import { T, forwardEventHandlers } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        
        
        

        export const ref = new Group()

				

        

        const gltf = useGltf('/src/lib/components/models/barrel.glb')
    

			const component = forwardEventHandlers()
    </script>

		<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
			{#await gltf}
				<slot name="fallback" />
			{:then gltf}
				<T.Mesh castShadow receiveShadow geometry={gltf.nodes.Mesh_barrel.geometry} material={gltf.materials.wood} />
<T.Mesh castShadow receiveShadow geometry={gltf.nodes.Mesh_barrel_1.geometry} material={gltf.materials.rock} />
<T.Mesh castShadow receiveShadow geometry={gltf.nodes.Mesh_barrel_2.geometry} material={gltf.materials.woodDark} />
<T.Mesh castShadow receiveShadow geometry={gltf.nodes.Mesh_barrel_3.geometry} material={gltf.materials.metal} />

			{:catch error}
				<slot name="error" {error} />
			{/await}

			<slot {ref} />
		</T>
	