
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 static/models/fenceCorner.glb
-->




    <script>

				
	
        import { Group } from 'three'
        import { T, forwardEventHandlers } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        
        
        

        export const ref = new Group()

				

        

        const gltf = useGltf('/models/fenceCorner.glb')
    

			const component = forwardEventHandlers()
    </script>

		<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
			{#await gltf}
				<slot name="fallback" />
			{:then gltf}
				<T.Mesh geometry={gltf.nodes.Mesh_fenceCorner.geometry} material={gltf.materials.woodDark} />
<T.Mesh geometry={gltf.nodes.Mesh_fenceCorner_1.geometry} material={gltf.materials.wood} />

			{:catch error}
				<slot name="error" {error} />
			{/await}

			<slot {ref} />
		</T>
	