<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 src/lib/components/models/TeleporterBase.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/src/lib/components/models/TeleporterBase.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={100}>
      <T.Mesh geometry={gltf.nodes.Props_Base_1.geometry} material={gltf.materials.DarkGrey} />
      <T.Mesh geometry={gltf.nodes.Props_Base_2.geometry} material={gltf.materials.Main} />
      <T.Mesh geometry={gltf.nodes.Props_Base_3.geometry} material={gltf.materials.Accent} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
