
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 src/lib/components/models/chracter.glb -s
-->




    <script>

				
	
        import { Group } from 'three'
        import { T, forwardEventHandlers } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        
        
        

        export const ref = new Group()

				

        

        const gltf = useGltf('/src/lib/components/models/chracter.glb')
    

			const component = forwardEventHandlers()
    </script>

		<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
			{#await gltf}
				<slot name="fallback" />
			{:then gltf}
				<T is={gltf.nodes.LeftFootCtrl} />
<T is={gltf.nodes.RightFootCtrl} />
<T is={gltf.nodes.HipsCtrl} />
<T.SkinnedMesh castShadow receiveShadow geometry={gltf.nodes.characterMedium.geometry} material={gltf.materials.skin} skeleton={gltf.nodes.characterMedium.skeleton} />

			{:catch error}
				<slot name="error" {error} />
			{/await}

			<slot {ref} />
		</T>
	