
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 src/lib/components/models/crateStrong.glb
-->




    <script>

				
	
        import { Group, MeshStandardMaterial } from 'three'
        import { T, forwardEventHandlers } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        
        
        

        export const ref = new Group()

				

        

        const gltf = useGltf('/static/models/crateStrong.glb')
    

			const component = forwardEventHandlers()
    </script>

		<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
			{#await gltf}
				<slot name="fallback" />
			{:then gltf}
				<T.Mesh geometry={gltf.nodes.Mesh_crateStrong.geometry} material={new MeshStandardMaterial({color: "gray", metalness : 0.8, roughness: 0.2})} />
<T.Mesh geometry={gltf.nodes.Mesh_crateStrong_1.geometry} material={gltf.materials.woodDark} />
<T.Mesh geometry={gltf.nodes.Mesh_crateStrong_2.geometry} material={gltf.materials.wood} />

			{:catch error}
				<slot name="error" {error} />
			{/await}

			<slot {ref} />
		</T>
	