<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 src/lib/components/models/FireGrenade.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/src/lib/components/models/FireGrenade.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={32.81}>
      <T.Mesh geometry={gltf.nodes.FireGrenade_1.geometry} material={gltf.materials.Red} />
      <T.Mesh geometry={gltf.nodes.FireGrenade_2.geometry} material={gltf.materials.Black} />
      <T.Mesh geometry={gltf.nodes.FireGrenade_3.geometry} material={gltf.materials.Grey} />
      <T.Mesh geometry={gltf.nodes.FireGrenade_4.geometry} material={gltf.materials.DarkRed} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
