<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 src/lib/components/models/GasCan.glb
-->

<script>
  import { Group, MeshStandardMaterial } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/src/lib/components/models/GasCan.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={84.41}>
      <T.Mesh geometry={gltf.nodes.GasCan_1.geometry} material={new MeshStandardMaterial({color: "red"})} />
      <T.Mesh geometry={gltf.nodes.GasCan_2.geometry} material={new MeshStandardMaterial({color: "red"})} />
      <T.Mesh geometry={gltf.nodes.GasCan_3.geometry} material={new MeshStandardMaterial({color: "black"})} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
