<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 src/lib/components/models/Landmine.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/src/lib/components/models/Landmine.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]} scale={[39.28, 39.28, 11.85]}>
      <T.Mesh geometry={gltf.nodes.Landmine_1.geometry} material={gltf.materials.DarkGrey} />
      <T.Mesh geometry={gltf.nodes.Landmine_2.geometry} material={gltf.materials.Red} />
      <T.Mesh geometry={gltf.nodes.Landmine_3.geometry} material={gltf.materials.Grey} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
