<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 src/lib/components/models/Rover.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/src/lib/components/models/Rover.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Wheel_4001.geometry}
      material={gltf.materials.Atlas}
      position={[-1.8, 0.53, 1.9]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={gltf.nodes.Wheel_5.geometry}
      material={gltf.materials.Atlas}
      position={[1.8, 0.53, 1.9]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={gltf.nodes.Wheel_1002.geometry}
      material={gltf.materials.Atlas}
      position={[1.8, 0.53, -1.9]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={gltf.nodes.Wheel_4002.geometry}
      material={gltf.materials.Atlas}
      position={[-1.8, 0.53, -1.9]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={gltf.nodes.Rover_1.geometry}
      material={gltf.materials.Atlas}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
