<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 src/lib/components/models/building.glb -s
-->

<script>
  import { Group, MeshStandardMaterial } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  let material = new MeshStandardMaterial({color: '#000', roughness: 0, });
  let window = new MeshStandardMaterial({color: 'cyan', roughness: 0, emissive: 'cyan', emissiveIntensity: 0});
  const gltf = useGltf('/src/lib/components/models/building.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.small_buildingA_1.geometry}
      material={window}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.small_buildingA_1_1.geometry}
      material={material}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.small_buildingA_1_2.geometry}
      material={material}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.small_buildingA_1_3.geometry}
      material={gltf.materials.door}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
