<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 src/lib/components/models/Teleporter.glb --shadow --output
-->

<script>
  import { ConeGeometry, Group, MeshStandardMaterial } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/src/lib/components/models/Teleporter.glb')
  const gold= new MeshStandardMaterial({color: '#d4af37', roughness: 0, matalness: 0.5});

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={100}>
      <T.Mesh geometry={new ConeGeometry(0.5, 1, 40, 20, true)} material={new MeshStandardMaterial({color: 'teal', trasparent:true, opacity: 0.4})}/>
      <T.Mesh geometry={gltf.nodes.Props_Base_1.geometry} material={gltf.materials.DarkGrey} />
      <T.Mesh geometry={gltf.nodes.Props_Base_2.geometry} material={gltf.materials.Main} />
      <T.Mesh geometry={gltf.nodes.Props_Base_3.geometry} material={gold} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
